import React from 'react'

const ImageCard = ( prompts ) => {

  const {imageUrl, name, prompt, _id} = prompts.prompt;

  return (
    <div className="m-6 p-5 flex flex-col rounded-xl bg-gray-200 w-[425px] hover:shadow-2xl">
        <div className=" rounded-lg overflow-hidden"><img src={imageUrl} alt={prompt} /></div>
        <p className=" mt-2 pl-2 text-xl font-semibold ">{prompt}</p>
        <p className="pl-2 text-sm">Generated by <span className="font-semibold">{name}</span></p>
    </div>
  )
}

export default ImageCard